//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using UsersAPI;

//#nullable disable

//namespace WebApplication3.Migrations
//{
//    [DbContext(typeof(UsersDbContext))]
//    [Migration("20260218171114_Init")]
//    partial class Init
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

//            modelBuilder.Entity("UsersAPI.Models.User", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<DateOnly>("Birthday")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Gender")
//                        .IsRequired()
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("TEXT");

//                    b.HasKey("Id");

//                    b.ToTable("Users");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
